### PR TITLE
Problem: deployment scripts unavailable for inspection on Instances

### PR DESCRIPTION
**Pull request by lenards**
## Overview 

Link instance-scripts so they are inspectable

Increase the debuggability of instance-scripts by allowing them to remain available for inspection after the instance deployment activity is complete.

This work makes the deploy scripts available under:
- `/etc/atmo/instance-scripts-available/`

---

## Terminology:

We will refer to scripts associated with an instance at the time of "launch" as "deploy scripts", not *boot scripts*.

For Deploy Scripts, this "association" at launch time is the most common.
A deploy script *could* be _included_ with an Image by the author of
that Image. For this commit (and the containing PR), we are not trying
to handle nor account for deploy scripts included in Images. This case
is referred to by Steve Gregory (the case of deploy scripts included
"with an Image") as "Post Scripts". These deploy scripts included with
an Image will always be run **last** - which seems to be why they were
called this. We will endeavor for a "new" name for them at some point.
At this time - they do not appear to be working (as expected) ([ATMO-2137](https://pods.iplantcollaborative.org/jira/browse/ATMO-2137)).

---

## Description

This links scripts associated at instance "launch time" into a directory that is _inspectable_ after execution. It borrows from the pattern that you see in uWSGI & Nginx regarding "apps" and "sites (respectively).

For Nginx, you have a site's configuration "sites-available" and when it is active (or enabled), the site's configuration is symlinked into the "sites-enabled" directory:

Available Nginx sites:
```
ls -lha /etc/nginx/sites-available/
total 16K
drwxr-xr-x 2 root root 4.0K Jan 19 21:53 .
drwxr-xr-x 9 root root 4.0K Jan 19 21:53 ..
-rw-r--r-- 1 root root 2.4K Jan 18  2017 default
-rw-r--r-- 1 root root 1.9K Jan 19 19:11 site.conf
```

Enabled Nginx Sites:
```
ls -lha /etc/nginx/sites-enabled/
total 8.0K
drwxr-xr-x 2 root root 4.0K Nov 13 23:34 .
drwxr-xr-x 9 root root 4.0K Jan 19 21:53 ..
lrwxrwxrwx 1 root root   36 Nov 13 23:34 site.conf -> /etc/nginx/sites-available/site.conf
```

Here - we take the "deploy scripts" copy them into the "available" directory:

- /etc/atmo/instance-scripts-available/

Them, we symlink them into location the Ansible Role expects them to be:

- /etc/atmo/instance-scripts.d/

This approach of removing from "instance-scripts.d" was used to help avoid any of "re-executing" scripts.

Output examples from an Instance are included in the Details below:

<details>

**Note** - I made a typo in the name of the directory that appears in these detailed output examples. 

It has been corrected (in commit aa8436f0b586d31444b5241a64427ef39085e0bc):
```
INSTANCE_SCRIPT_AVAILABLE_DIR: "{{ SCRIPTS_ROOT }}/instance-scripts-available"
```

I have left the error in the output for transparency. 

For an instance that has associated "launch" time deploy script (e.g. deployment scripts), you'll see the new directory under `/etc/atmo` (the root directory of where scripts are targeted during Instance Deployment Automation):

```
lenards@vm142-33:/etc/atmo$ ls -lha
total 32K
drwxr-xr-x   5 root root 4.0K Feb 19 10:02 .
drwxr-xr-x 114 root root  12K Feb 19 10:10 ..
drwxr-xr-x   2 root root 4.0K Feb 19 10:02 instance-scripts-avaiable
drwxr-xr-x   2 root root 4.0K Feb 19 10:02 instance-scripts.d
drwxr-xr-x   2 root root 4.0K Jan 11  2017 post-scripts.d
-rw-r--r--   1 root root  450 Feb 19 10:02 README.txt
```

Anything that executed during the "Deploying" activity of Instance Deployment Automation will appear under `/etc/atmo/instance-scripts-available/` (sic)
```
lenards@vm142-33:/etc/atmo$ ls -lha instance-scripts-avaiable/
total 24K
drwxr-xr-x 2 root root 4.0K Feb 19 10:02 .
drwxr-xr-x 5 root root 4.0K Feb 19 10:02 ..
-rwxr--r-- 1 root root   43 Feb 19 10:02 raw_sync_test
-rwxr--r-- 1 root root   45 Feb 19 10:02 raw_test_test
-rwxr--r-- 1 root root   60 Feb 19 10:02 raw_tsk_tsk_tsk_test
-rwxr--r-- 1 root root   52 Feb 19 10:02 raw_tst_tsk_test
```

Previously, you would be able to see that the deploy script ran in the `syslog` for the Instance. But you would *not* necessarily know if that deploy script had an updated change in it that you made (if you're in the middle of development or correcting a problem). 

So the "available" directory allows for the inspection of the executed scripts:
```
lenards@vm142-33:/etc/atmo$ cat instance-scripts-avaiable/raw_test_test && echo -ne "\n."
#!/bin/bash

echo "Here we are, ${ATMO_USER}"
.lenards@vm142-33:/etc/atmo$ 
```

Note, that the script will be symbolically linked into `/etc/atmo/instance-scripts.d` and then deleted (removed) after they are executed:
```
lenards@vm142-33:/etc/atmo$ ls -lha instance-scripts.d/
total 8.0K
drwxr-xr-x 2 root root 4.0K Feb 19 10:02 .
drwxr-xr-x 5 root root 4.0K Feb 19 10:02 ..
```

A README.txt is provided under `/etc/atmo` to try to guide or assist someone that is looking on the instance and trying to inspect the scripts. Please suggest edits if they think it is not clear nor depicting the deployment script process effectively.

Here is an example of the current text:
```
lenards@vm142-33:/etc/atmo$ cat README.txt 
# Atmosphere Deployment Scripts

"Deployment Scripts" are generalized term for scripts that are included
per instance launch and scripts that are part of an Image. Previously,
these scripts were referred to as "boot" scripts. However, the timing
of when scripts are run is after the actual "boot" process.

Scripts that were included "at launch" by the Instance creator can be
found in the following directory:

- /etc/atmo/instance-scripts-avaiable
```

</details>

## See also

[ATMO-2137](https://pods.iplantcollaborative.org/jira/browse/ATMO-2137)

### CODE REVIEW

**Comment by cdosborn** [comment]
Looks good. I'll build this today.

**Comment by cdosborn** [comment]
Ran into a small issue. See https://github.com/lenards/atmosphere-ansible/pull/1/files

**Comment by cdosborn** [comment]
Thanks @lenards

**Comment by lenards** [comment]
@cdosborn - sorry I didn't get to triaging and fixing the issues with `POST_SCRIPTS`.

**Comment by cdosborn** [comment]
No sweat, should be an easy extension of the work here.

**Pull request merged**
