### PR TITLE
Add cyverse_backup.sh install role from Galaxy

### PR DESCRIPTION
**Pull request by calvinmclean**
Adds [this Galaxy role](https://galaxy.ansible.com/CyVerse-Ansible/atmo-backup/) to the `30_post_user_install.yml` playbook.

The role will put the `cyverse_backup.sh` script in `/opt` and link it to `/usr/local/bin`

### CODE REVIEW

**Comment by edwins** [comment]
in ansible/playbooks/instance_deploy/30_post_user_install.yml, shouldn't the role name be "ansible-atmo-backup" rather than "atmo-backup" (per requirements.yml)?

**Comment by calvinmclean** [comment]
@edwins Good catch. I noticed that the [ansible-irods-icommands](https://github.com/CyVerse-Ansible/ansible-irods-icommands) was referred to by `irods-icommands` in Galaxy and `requirements.yml`. So I created the second commit to change mine to match, but missed a line. I'll push up another commit

**Comment by c-mart** [comment]
One more catch: https://github.com/calvinmclean/atmosphere-ansible/pull/4 Gotta actually run the command to install the role. Thanks, Calvin!

**Comment by calvinmclean** [comment]
Merged :+1: @c-mart Edwin asked me to change the license and add a tag to `meta/main.yml`. Then after refreshing the role on Galaxy, I should run the install command again and commit, right?

**Comment by c-mart** [comment]
@calvinmclean yes!

**Comment by calvinmclean** [comment]
@c-mart done

**Pull request merged**
